# TMB calculation

configfile: 'config.yaml'

rule all:
    input:
        'final??'

rule fix_maf_space:
    input: 'data/mc3.v0.2.8.PUBLIC.maf'
    output: 'processed_data/mc3.maf'
    message: 'Changing line breaks of the MAF file'
    shell: 'perl -lne \'s/\\r//; print "$_";\' {input} > {output}'

rule find_maf_coord:
    input: 'processed_data/mc3.maf'
    output: 'processed_data/mc3.bed'
    message: 'Extracting mutations coordinates'
    shell: 'cut -f5-7 {input} | tail -n +2 | sort -k1,1 -k2,2n > {output}'

rule remove_maf_dupes:
    input: 'processed_data/mc3.bed'
    output: 'processed_data/mc3_merged.bed'
    message: 'Removing duplicates coordinates'
    shell: 'bedtools merge -i {input} > {output}'

rule ccds_format:
    input: 'data/CCDS.20131129.txt'
    output: 'processed_data/CCDS.bed'
    message: 'Making a BED file from exon coordinates'
    shell: 'cut -f1,8,9 {input} | sort -k1,1 -k2,2n | tail -n +3 > {output}'

rule find_intersect:
    input:
        maf_file='processed_data/mc3_merged.bed',
        CCDS_file='processed_data/CCDS.bed'
    output: 'processed_data/mut_at_CCDS.bed'
    message: 'Finding the mutation coordinates at exonic regions'
    shell: 'bedtools intersect -sorted -wa -a {input.maf_file} -b {input.CCDS_file} > {output}'

rule remove_dupes:
    input: 'processed_data/mut_at_CCDS.bed'
    output: 'processed_data/mut_no_dup.bed'
    message: 'Removing duplicate exonic mutations'
    shell: 'bedtools merge -i {input} > {output}'
